# Generated by Django 3.1.7 on 2021-03-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_profile_photo',
            field=models.ImageField(default='book_img/default.jpg', null=True, upload_to='book_img'),
        ),
    ]
