# Generated by Django 3.1.7 on 2021-03-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210319_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookanduser',
            name='rate_book_by_user',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
